version: '3.3'
services:

  jenkins:
    image: jenkins.nginx.docker:lts
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - '2022:22'
      - '50000:50000'
      - '50022:50022'
    volumes:
      - ${JENKINS_DEFAULT_HOME:-JENKINS_DEFAULT_HOME is not defined}
      - ${DOCKER_SOCK:-DOCKER_SOCK is not defined}
    environment:
      - UID_JENKINS=${UID_JENKINS:-1000}
      - GID_JENKINS=${GID_JENKINS:-1000}
      - JENKINS_OPTS=${JENKINS_OPTS:-"--prefix=/jenkins"}
    restart: always
  
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus3
    environment:
       - NEXUS_CONTEXT=${NEXUS_CONTEXT}:NEXUS_CONTEXT is not defined
    ports:
       - "8081:8081"
       - "8123:8123"  
    volumes:
       - ${NEXUS_DATA:-NEXUS_DATA}
    restart: always     

  sonarqube:
    image: sonarqube:6.7.1
    restart: unless-stopped
    environment:
      - SONARQUBE_JDBC_USERNAME=${SONARQUBE_JDBC_USERNAME}:SONARQUBE_JDBC_USERNAME is not defined
      - SONARQUBE_JDBC_PASSWORD=${SONARQUBE_JDBC_PASSWORD}:SONARQUBE_JDBC_PASSWORD is not defined
      - SONARQUBE_JDBC_URL=${SONARQUBE_JDBC_URL}:SONARQUBE_JDBC_URL is not defined
    command: ${SONARQUBE_CONTEXT}:SONARQUBE_CONTEXT is not defined    
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - ${SONARQUBE_CONF:-SONARQUBE_CONF is not defined}
      - ${SONARQUBE_DATA:-SONARQUBE_DATA is not defined}
      - ${SONARQUBE_EXT:-SONARQUBE_EXT is not defined}
      - ${SONARQUBE_PLUGINS:-SONARQUBE_PLUGINS is not defined}
    restart: always    

  sonar-postgresql:
    image: postgres:10.1
    container_name: sonar-postgresql
    environment:
      - POSTGRES_USER=${SONARQUBE_JDBC_USERNAME}:SONARQUBE_JDBC_USERNAME is not defined
      - POSTGRES_PASSWORD=${SONARQUBE_JDBC_PASSWORD}:SONARQUBE_JDBC_PASSWORD is not defined
      - POSTGRES_DB=sonarube${SONARQUBE_JDBC_URL}:SONARQUBE_JDBC_URL is not defined
    volumes:
      - ${SONARQUBE_PSQL:-SONARQUBE_PSQL is not defined}
      - ${SONARQUBE_PSQL_DATA:-SONARQUBE_PSQL_DATA is not defined} 
    ports:
      - "5432:5432"
    restart: always
       
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${NGINX_DEFAULT_CONF:-./nginx/default.con}:/etc/nginx/conf.d/default.conf
      - ${NGINX_LOGS:-NGINX_LOGS is not defined}
      - ${NGINX_SSL_CERT:-NGINX_SSL_CERT is not defined} 
      - ${NGINX_SSL_KEY:-NGINX_SSL_KEY is not defined}
      - ${NGINX_WEB:-NGINX_WEB is not defined} 
    restart: always
